# Código para el cubo semántico que recibe (op1,op2,operator)
# Estructura de datos utilizada: diccionario

class semanticCube:
    #Se inicializa el cubo semántico
    def __init__(self):
        self.SemCube = {
            # Combinaciones int
            ('int', 'int', '+'): 'int',
            ('int', 'int', '-'): 'int',
            ('int', 'int', '*'): 'int',
            ('int', 'int', '/'): 'float',
            ('int', 'int', '='): 'int',
            ('int', 'int', '=='): 'bool',
            ('int', 'int', '<'): 'bool',
            ('int', 'int', '>'): 'bool',
            ('int', 'int', '<='): 'bool',
            ('int', 'int', '>='): 'bool',
            ('int', 'int', '!='): 'bool',
            ('int', 'int', '|'): 'error',
            ('int', 'int', '&'): 'error',

            ('int', 'float', '+'): 'float',
            ('int', 'float', '-'): 'float',
            ('int', 'float', '*'): 'float',
            ('int', 'float', '/'): 'float',
            ('int', 'float', '='): 'int',
            ('int', 'float', '=='): 'bool',
            ('int', 'float', '<'): 'bool',
            ('int', 'float', '>'): 'bool',
            ('int', 'float', '<='): 'bool',
            ('int', 'float', '>='): 'bool',
            ('int', 'float', '!='): 'bool',
            ('int', 'float', '|'): 'error',
            ('int', 'float', '&'): 'error',

            ('int', 'char', '+'): 'error',
            ('int', 'char', '-'): 'error',
            ('int', 'char', '*'): 'error',
            ('int', 'char', '/'): 'error',
            ('int', 'char', '='): 'error',
            ('int', 'char', '=='): 'error',
            ('int', 'char', '<'): 'error',
            ('int', 'char', '>'): 'error',
            ('int', 'char', '<='): 'error',
            ('int', 'char', '>='): 'error',
            ('int', 'char', '!='): 'error',
            ('int', 'char', '|'): 'error',
            ('int', 'char', '&'): 'error',

            ('int', 'string', '+'): 'error',
            ('int', 'string', '-'): 'error',
            ('int', 'string', '*'): 'error',
            ('int', 'string', '/'): 'error',
            ('int', 'string', '='): 'error',
            ('int', 'string', '=='): 'error',
            ('int', 'string', '<'): 'error',
            ('int', 'string', '>'): 'error',
            ('int', 'string', '<='): 'error',
            ('int', 'string', '>='): 'error',
            ('int', 'string', '!='): 'error',
            ('int', 'string', '|'): 'error',
            ('int', 'string', '&'): 'error',

            ('int', 'dataframe', '+'): 'error',
            ('int', 'dataframe', '-'): 'error',
            ('int', 'dataframe', '*'): 'error',
            ('int', 'dataframe', '/'): 'error',
            ('int', 'dataframe', '='): 'error',
            ('int', 'dataframe', '=='): 'error',
            ('int', 'dataframe', '<'): 'error',
            ('int', 'dataframe', '>'): 'error',
            ('int', 'dataframe', '<='): 'error',
            ('int', 'dataframe', '>='): 'error',
            ('int', 'dataframe', '!='): 'error',
            ('int', 'dataframe', '|'): 'error',
            ('int', 'dataframe', '&'): 'error',

            # Combinaciones float
            ('float', 'int', '+'): 'float',
            ('float', 'int', '-'): 'float',
            ('float', 'int', '*'): 'float',
            ('float', 'int', '/'): 'float',
            ('float', 'int', '='): 'float',
            ('float', 'int', '=='): 'bool',
            ('float', 'int', '<'): 'bool',
            ('float', 'int', '>'): 'bool',
            ('float', 'int', '<='): 'bool',
            ('float', 'int', '>='): 'bool',
            ('float', 'int', '!='): 'bool',
            ('float', 'int', '|'): 'error',
            ('float', 'int', '&'): 'error',

            ('float', 'float', '+'): 'float',
            ('float', 'float', '-'): 'float',
            ('float', 'float', '*'): 'float',
            ('float', 'float', '/'): 'float',
            ('float', 'float', '='): 'float',
            ('float', 'float', '=='): 'bool',
            ('float', 'float', '<'): 'bool',
            ('float', 'float', '>'): 'bool',
            ('float', 'float', '<='): 'bool',
            ('float', 'float', '>='): 'bool',
            ('float', 'float', '!='): 'bool',
            ('float', 'float', '|'): 'error',
            ('float', 'float', '&'): 'error',

            ('float', 'char', '+'): 'error',
            ('float', 'char', '-'): 'error',
            ('float', 'char', '*'): 'error',
            ('float', 'char', '/'): 'error',
            ('float', 'char', '='): 'error',
            ('float', 'char', '=='): 'error',
            ('float', 'char', '<'): 'error',
            ('float', 'char', '>'): 'error',
            ('float', 'char', '<='): 'error',
            ('float', 'char', '>='): 'error',
            ('float', 'char', '!='): 'error',
            ('float', 'char', '|'): 'error',
            ('float', 'char', '&'): 'error',

            ('float', 'string', '+'): 'error',
            ('float', 'string', '-'): 'error',
            ('float', 'string', '*'): 'error',
            ('float', 'string', '/'): 'error',
            ('float', 'string', '='): 'error',
            ('float', 'string', '=='): 'error',
            ('float', 'string', '<'): 'error',
            ('float', 'string', '>'): 'error',
            ('float', 'string', '<='): 'error',
            ('float', 'string', '>='): 'error',
            ('float', 'string', '!='): 'error',
            ('float', 'string', '|'): 'error',
            ('float', 'string', '&'): 'error',

            ('float', 'dataframe', '+'): 'error',
            ('float', 'dataframe', '-'): 'error',
            ('float', 'dataframe', '*'): 'error',
            ('float', 'dataframe', '/'): 'error',
            ('float', 'dataframe', '='): 'error',
            ('float', 'dataframe', '=='): 'error',
            ('float', 'dataframe', '<'): 'error',
            ('float', 'dataframe', '>'): 'error',
            ('float', 'dataframe', '<='): 'error',
            ('float', 'dataframe', '>='): 'error',
            ('float', 'dataframe', '!='): 'error',
            ('float', 'dataframe', '|'): 'error',
            ('float', 'dataframe', '&'): 'error',

            # Combinaciones char
            ('char', 'int', '+'): 'error',
            ('char', 'int', '-'): 'error',
            ('char', 'int', '*'): 'error',
            ('char', 'int', '/'): 'error',
            ('char', 'int', '='): 'error',
            ('char', 'int', '=='): 'error',
            ('char', 'int', '<'): 'error',
            ('char', 'int', '>'): 'error',
            ('char', 'int', '<='): 'error',
            ('char', 'int', '>='): 'error',
            ('char', 'int', '!='): 'error',
            ('char', 'int', '|'): 'error',
            ('char', 'int', '&'): 'error',

            ('char', 'float', '+'): 'error',
            ('char', 'float', '-'): 'error',
            ('char', 'float', '*'): 'error',
            ('char', 'float', '/'): 'error',
            ('char', 'float', '='): 'error',
            ('char', 'float', '=='): 'error',
            ('char', 'float', '<'): 'error',
            ('char', 'float', '>'): 'error',
            ('char', 'float', '<='): 'error',
            ('char', 'float', '>='): 'error',
            ('char', 'float', '!='): 'error',
            ('char', 'float', '|'): 'error',
            ('char', 'float', '&'): 'error',

            ('char', 'char', '+'): 'error',
            ('char', 'char', '-'): 'error',
            ('char', 'char', '*'): 'error',
            ('char', 'char', '/'): 'error',
            ('char', 'char', '='): 'char',
            ('char', 'char', '=='): 'bool',
            ('char', 'char', '<'): 'error',
            ('char', 'char', '>'): 'error',
            ('char', 'char', '<='): 'error',
            ('char', 'char', '>='): 'error',
            ('char', 'char', '!='): 'bool',
            ('char', 'char', '|'): 'error',
            ('char', 'char', '&'): 'error',

            ('char', 'string', '+'): 'string',
            ('char', 'string', '-'): 'error',
            ('char', 'string', '*'): 'error',
            ('char', 'string', '/'): 'error',
            ('char', 'string', '='): 'error',
            ('char', 'string', '=='): 'bool',
            ('char', 'string', '<'): 'error',
            ('char', 'string', '>'): 'error',
            ('char', 'string', '<='): 'error',
            ('char', 'string', '>='): 'error',
            ('char', 'string', '!='): 'bool',
            ('char', 'string', '|'): 'error',
            ('char', 'string', '&'): 'error',

            ('char', 'dataframe', '+'): 'error',
            ('char', 'dataframe', '-'): 'error',
            ('char', 'dataframe', '*'): 'error',
            ('char', 'dataframe', '/'): 'error',
            ('char', 'dataframe', '='): 'error',
            ('char', 'dataframe', '=='): 'error',
            ('char', 'dataframe', '<'): 'error',
            ('char', 'dataframe', '>'): 'error',
            ('char', 'dataframe', '<='): 'error',
            ('char', 'dataframe', '>='): 'error',
            ('char', 'dataframe', '!='): 'error',
            ('char', 'dataframe', '|'): 'error',
            ('char', 'dataframe', '&'): 'error',

            # Combinaciones string
            ('string', 'int', '+'): 'error',
            ('string', 'int', '-'): 'error',
            ('string', 'int', '*'): 'error',
            ('string', 'int', '/'): 'error',
            ('string', 'int', '='): 'error',
            ('string', 'int', '=='): 'error',
            ('string', 'int', '<'): 'error',
            ('string', 'int', '>'): 'error',
            ('string', 'int', '<='): 'error',
            ('string', 'int', '>='): 'error',
            ('string', 'int', '!='): 'error',
            ('string', 'int', '|'): 'error',
            ('string', 'int', '&'): 'error',

            ('string', 'float', '+'): 'error',
            ('string', 'float', '-'): 'error',
            ('string', 'float', '*'): 'error',
            ('string', 'float', '/'): 'error',
            ('string', 'float', '='): 'error',
            ('string', 'float', '=='): 'error',
            ('string', 'float', '<'): 'error',
            ('string', 'float', '>'): 'error',
            ('string', 'float', '<='): 'error',
            ('string', 'float', '>='): 'error',
            ('string', 'float', '!='): 'error',
            ('string', 'float', '|'): 'error',
            ('string', 'float', '&'): 'error',

            ('string', 'char', '+'): 'string',
            ('string', 'char', '-'): 'error',
            ('string', 'char', '*'): 'error',
            ('string', 'char', '/'): 'error',
            ('string', 'char', '='): 'char',
            ('string', 'char', '=='): 'bool',
            ('string', 'char', '<'): 'error',
            ('string', 'char', '>'): 'error',
            ('string', 'char', '<='): 'error',
            ('string', 'char', '>='): 'error',
            ('string', 'char', '!='): 'bool',
            ('string', 'char', '|'): 'error',
            ('string', 'char', '&'): 'error',

            ('string', 'string', '+'): 'string',
            ('string', 'string', '-'): 'error',
            ('string', 'string', '*'): 'error',
            ('string', 'string', '/'): 'error',
            ('string', 'string', '='): 'string',
            ('string', 'string', '=='): 'bool',
            ('string', 'string', '<'): 'error',
            ('string', 'string', '>'): 'error',
            ('string', 'string', '<='): 'error',
            ('string', 'string', '>='): 'error',
            ('string', 'string', '!='): 'bool',
            ('string', 'string', '|'): 'error',
            ('string', 'string', '&'): 'error',

            ('string', 'dataframe', '+'): 'error',
            ('string', 'dataframe', '-'): 'error',
            ('string', 'dataframe', '*'): 'error',
            ('string', 'dataframe', '/'): 'error',
            ('string', 'dataframe', '='): 'error',
            ('string', 'dataframe', '=='): 'error',
            ('string', 'dataframe', '<'): 'error',
            ('string', 'dataframe', '>'): 'error',
            ('string', 'dataframe', '<='): 'error',
            ('string', 'dataframe', '>='): 'error',
            ('string', 'dataframe', '!='): 'error',
            ('string', 'dataframe', '|'): 'error',
            ('string', 'dataframe', '&'): 'error',

            # Combinaciones dataframe
            ('dataframe', 'int', '+'): 'error',
            ('dataframe', 'int', '-'): 'error',
            ('dataframe', 'int', '*'): 'error',
            ('dataframe', 'int', '/'): 'error',
            ('dataframe', 'int', '='): 'error',
            ('dataframe', 'int', '=='): 'error',
            ('dataframe', 'int', '<'): 'error',
            ('dataframe', 'int', '>'): 'error',
            ('dataframe', 'int', '<='): 'error',
            ('dataframe', 'int', '>='): 'error',
            ('dataframe', 'int', '!='): 'error',
            ('dataframe', 'int', '|'): 'error',
            ('dataframe', 'int', '&'): 'error',

            ('dataframe', 'float', '+'): 'error',
            ('dataframe', 'float', '-'): 'error',
            ('dataframe', 'float', '*'): 'error',
            ('dataframe', 'float', '/'): 'error',
            ('dataframe', 'float', '='): 'error',
            ('dataframe', 'float', '=='): 'error',
            ('dataframe', 'float', '<'): 'error',
            ('dataframe', 'float', '>'): 'error',
            ('dataframe', 'float', '<='): 'error',
            ('dataframe', 'float', '>='): 'error',
            ('dataframe', 'float', '!='): 'error',
            ('dataframe', 'float', '|'): 'error',
            ('dataframe', 'float', '&'): 'error',

            ('dataframe', 'char', '+'): 'error',
            ('dataframe', 'char', '-'): 'error',
            ('dataframe', 'char', '*'): 'error',
            ('dataframe', 'char', '/'): 'error',
            ('dataframe', 'char', '='): 'error',
            ('dataframe', 'char', '=='): 'error',
            ('dataframe', 'char', '<'): 'error',
            ('dataframe', 'char', '>'): 'error',
            ('dataframe', 'char', '<='): 'error',
            ('dataframe', 'char', '>='): 'error',
            ('dataframe', 'char', '!='): 'error',
            ('dataframe', 'char', '|'): 'error',
            ('dataframe', 'char', '&'): 'error',

            ('dataframe', 'string', '+'): 'error',
            ('dataframe', 'string', '-'): 'error',
            ('dataframe', 'string', '*'): 'error',
            ('dataframe', 'string', '/'): 'error',
            ('dataframe', 'string', '='): 'error',
            ('dataframe', 'string', '=='): 'error',
            ('dataframe', 'string', '<'): 'error',
            ('dataframe', 'string', '>'): 'error',
            ('dataframe', 'string', '<='): 'error',
            ('dataframe', 'string', '>='): 'error',
            ('dataframe', 'string', '!='): 'error',
            ('dataframe', 'string', '|'): 'error',
            ('dataframe', 'string', '&'): 'error',

            ('dataframe', 'dataframe', '+'): 'error',
            ('dataframe', 'dataframe', '-'): 'error',
            ('dataframe', 'dataframe', '*'): 'error',
            ('dataframe', 'dataframe', '/'): 'error',
            ('dataframe', 'dataframe', '='): 'dataframe',
            ('dataframe', 'dataframe', '=='): 'error',
            ('dataframe', 'dataframe', '<'): 'error',
            ('dataframe', 'dataframe', '>'): 'error',
            ('dataframe', 'dataframe', '<='): 'error',
            ('dataframe', 'dataframe', '>='): 'error',
            ('dataframe', 'dataframe', '!='): 'error',
            ('dataframe', 'dataframe', '|'): 'error',
            ('dataframe', 'dataframe', '&'): 'error',

            # Combinaciones lee
            ('lee', 'int', ''): 'int',
            ('lee', 'float', ''): 'float',
            ('lee', 'char', ''): 'error',
            ('lee', 'string', ''): 'error',
            ('lee', 'dataframe', ''): 'char',

            # Combinaciones escribe
            ('escribe', 'int', ''): 'string',
            ('escribe', 'float', ''): 'string',
            ('escribe', 'char', ''): 'string',
            ('escribe', 'string', ''): 'string',
            ('escribe', 'dataframe', ''): 'error',

            # Combinaciones regresa
            ('regresa', 'int', ''): 'int',
            ('regresa', 'float', ''): 'float',
            ('regresa', 'char', ''): 'char',
            ('regresa', 'string', ''): 'string',
            ('regresa', 'dataframe', ''): 'dataframe'
        }

    #Obtiene el tipo de dato resultante
    def getResultType(self, operando1, operando2, operador):
        return self.SemCube[operando1, operando2, operador]